# Generated by Django 4.2.3 on 2023-10-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_remove_inasistencia_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inasistencia',
            name='imagen',
            field=models.ImageField(null=True, upload_to='inasistencia'),
        ),
    ]
