# Generated by Django 4.2.3 on 2023-11-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_inasistencia_fecha_alter_inasistencia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='inasistencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('estudiante', 'Estudiante'), ('profesor', 'Profesor'), ('Director', 'Director')], max_length=20),
        ),
    ]
